---
title: 'Long Term Data: Station02'
author: "Kriddie"
date: "2022-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

long term data for station 1

```{r library}
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(plotly)
library(here)
library(dplyr)
library(reshape2)
library(purrr)
library(sjmisc)
```

##read in wl02

```{r Hobo WL}
#First the Hobos

setwd(here::here("WaterLevel"))
all_files=list.files(pattern=".csv") #pulls out the csv files from CO2 folder
sites_rp = sub('_[^_]+$', '', all_files)
site_names=unique(sites_rp) #creates list of site names for following loop

site_names = "WL_02"
#site_names = site_names[c(2,3,5,6)]

#rm old files, if they exist
rm(WLData)
rm(Temp_WLData)

for (site in site_names){
  
  list1=list.files(pattern=site) #finds all files for the site
  sitelist_csv=grep(".csv",list1) #creates list of all files for site
  file_list=list1[sitelist_csv]
  
  #reads in files in list and appends
  for (file in file_list){
    if (!exists("WLData")){
      WLData <- read.csv(file, skip=1, header = FALSE, sep = ",",
                         quote = "\"",dec = ".", fill = TRUE, comment.char = "")
      
      if(str_contains(WLData[1,3],"Abs Pres, psi")){
        WLData <- WLData[-1,]
        colnames(WLData)=c("row","DateTime","WLPres_kpa","WLTemp_c")
        WLData <- WLData[2:4]
        WLData$WLPres_kpa <- as.numeric(as.character(WLData$WLPres_kpa), digits=6)
        WLData$WLTemp_c <- as.numeric(as.character(WLData$WLTemp_c), digits=5)
        WLData$WLPres_kpa <- WLData$WLPres_kpa*6.89476
        WLData$WLTemp_c <- (WLData$WLTemp_c - 32)/1.8000

      } else { 
        WLData <- WLData[-1,]
        colnames(WLData)=c("row","DateTime","WLPres_kpa","WLTemp_c")
        WLData <- WLData[2:4]
        WLData$WLPres_kpa <- as.numeric(as.character(WLData$WLPres_kpa), digits=6)
        WLData$WLTemp_c <- as.numeric(as.character(WLData$WLTemp_c), digits=5)
        }
      
#      WLData$DateTime <- as.POSIXct(WLData$DateTime, format="%m/%d/%y %I:%M:%S %p", tz="UTC")
    WLData$DateTime <- as.POSIXct(WLData$DateTime, tz="UTC",
           tryFormats = c("%m/%d/%y %I:%M:%S %p",
                          "%m/%d/%Y %H:%M"))
    }
    if (exists("WLData")){
      Temp_WLData <- read.csv(file, skip=1, header = FALSE, sep = ",",
                              quote = "\"",dec = ".", fill = TRUE, comment.char = "")  
#      
      
      if(str_contains(Temp_WLData[1,3],"Abs Pres, psi")){
        Temp_WLData <- Temp_WLData[-1,]
        colnames(Temp_WLData)=c("row","DateTime","WLPres_kpa","WLTemp_c")
        Temp_WLData <- Temp_WLData[2:4]
        Temp_WLData$WLPres_kpa <- as.numeric(as.character(Temp_WLData$WLPres_kpa), digits=6)
        Temp_WLData$WLTemp_c <- as.numeric(as.character(Temp_WLData$WLTemp_c), digits=5)
        Temp_WLData$WLPres_kpa <- Temp_WLData$WLPres_kpa*6.89476
        Temp_WLData$WLTemp_c <- (Temp_WLData$WLTemp_c - 32)/1.8000
        
        
      } else { 
        Temp_WLData <- Temp_WLData[-1,]
        colnames(Temp_WLData)=c("row","DateTime","WLPres_kpa","WLTemp_c")
        Temp_WLData <- Temp_WLData[2:4]
        Temp_WLData$WLPres_kpa <- as.numeric(as.character(Temp_WLData$WLPres_kpa), digits=6)
        Temp_WLData$WLTemp_c <- as.numeric(as.character(Temp_WLData$WLTemp_c), digits=5)
        }
      
#      Temp_WLData$DateTime <- as.POSIXct(Temp_WLData$DateTime, format="%m/%d/%y %I:%M:%S %p", tz="UTC")
          Temp_WLData$DateTime <- as.POSIXct(Temp_WLData$DateTime, tz="UTC",
           tryFormats = c("%m/%d/%y %I:%M:%S %p",
                          "%m/%d/%Y %H:%M"))
      
      
      WLData <- rbind(WLData, Temp_WLData)
      rm(Temp_WLData)
    }
    
  }
  WLData$DateTime <- round_date(WLData$DateTime, "15 mins")
  WLData$Station <- "Stn02"
  WLData=unique(WLData)
  assign((paste(site,sep="_")),WLData) #creates object with new appended data
  rm(WLData) #removes WLdata so that multiple sites aren't appended together
}

WL_02 <- WL_02%>%filter(WLPres_kpa != 62.566)
```
## plot 
plot the water level so that each station data can be cleaned

```{r plot, echo=FALSE}

##clean data

plot_ly(WL_02, x = ~DateTime, y = ~WLPres_kpa, type = 'scatter', mode = 'markers') 

```




```{r clean, echo=FALSE}
#Looks like there was a shift during the last download of 2022 field seaseon. entonces:
#64.347 - 62.987

#this is hard - it looks like the sensor moved 2x, once on the first dl of the field season, again in 

#WL_02$test <- WL_02$WLPres_kpa

#below is the best I got o far
WL_02[which(WL_02$DateTime > as.POSIXct("2022-07-27 10:15:00", tz="UTC")&WL_02$DateTime < as.POSIXct("2022-10-12 13:45:00", tz="UTC")),]$test <- 
  WL_02[which(WL_02$DateTime > as.POSIXct("2022-07-27 10:15:00", tz="UTC")&WL_02$DateTime < as.POSIXct("2022-10-12 13:45:00", tz="UTC")),]$test + (64.347-63.041)

WL_02[which(WL_02$DateTime < as.POSIXct("2022-10-12 13:45:00", tz="UTC")),]$test <- 
  WL_02[which(WL_02$DateTime < as.POSIXct("2022-10-12 13:45:00", tz="UTC")),]$test - (62.981-62.541)
#WL_02 <- WL_02%>%filter(WLPres_kpa != 62.566)
```

##Unresolved issues




```{r plot, echo=FALSE}

ggplot(WL_02, aes(x=DateTime, y=WLPres_kpa)) + geom_point()
```

## barometric data
now read in the barometric data

```{r baro loop, echo=FALSE}

###merge data with baro data###
setwd(here::here("Baro"))
all_files=list.files(pattern=".csv") #pulls out the csv files from WL folder in HOBOware folder
sites_rp=gsub("_.*","",all_files) #selects the correct pattern so as to seelct only desired files
site_names=unique(sites_rp) #creates list of site names for following loop

#rm old files, if they exsist
rm(BaroData)
rm(Temp_BaroData)

for (site in site_names){
  
  list1=list.files(pattern=site) #finds all files for the site
  sitelist_csv=grep(".csv",list1) #creates list of all files for site
  file_list=list1[sitelist_csv]
  
  #reads in files in list and appends
  for (file in file_list){
    if (!exists("BaroData")){
      BaroData <- read.csv(file, skip=10, header = TRUE, sep = ",",
                           quote = "\"",dec = ".", fill = TRUE, comment.char = "")
    }
    if (exists("BaroData")){
      Temp_BaroData <- read.csv(file, skip=10, header = TRUE, sep = ",",
                                quote = "\"",dec = ".", fill = TRUE, comment.char = "")  
      BaroData <- rbind(BaroData, Temp_BaroData)
      rm(Temp_BaroData)
    }
    
  }
  colnames(BaroData)=c("Date","Time","ms","AirPres_kpa","AirTemp_c")
  BaroData=unique(BaroData)
  BaroData$DateTime <- paste(BaroData$Date, BaroData$Time)
  BaroData$DateTime <- as.POSIXct(BaroData$DateTime, format="%m/%d/%Y %I:%M:%S %p", tz="UTC")
  BaroData$DateTime <- round_date(BaroData$DateTime, "15 mins")
  BaroData$ms <- NULL
  BaroData$Date <- NULL
  BaroData$Time <- NULL
  BaroData <- BaroData[,c(3,1,2)]
  BaroData=unique(BaroData)
  assign((paste(site,sep="_")),BaroData) #creates object with new appended data
  rm(BaroData) #removes WLdata so that multiple sites aren't appended together
}
```

### clean baro
```{r clean baro, echo=FALSE}

##clean BaroData
plot_ly(Baro%>%filter(DateTime > as.POSIXct("2021-06-11 00:00:00", tz = "UTC")), x = ~DateTime, y = ~AirPres_kpa, type = 'scatter', mode = 'markers') 

Baro <- Baro%>%filter(DateTime > as.POSIXct("2021-06-01 00:00:00", tz = "UTC"))

Baro <- Baro%>%filter(DateTime < as.POSIXct("2021-07-27 15:00:00", tz = "UTC")|
                          DateTime > as.POSIXct("2021-07-28 13:30:00", tz = "UTC"))

ggplot(Baro,aes(x=DateTime,y=AirPres_kpa))+ geom_point()

```

### correct for barometric pressure
```{r baro correct, echo=FALSE}

#correct for baro 

WL_01 <- left_join(Baro,WL_01,by="DateTime")

WL_01$Corrected_kpa <- WL_01$WLPres_kpa - WL_01$AirPres_kpa

#calculate total pressure to correct viasala readings
WL_01$Total_kpa <- 
  WL_01$WLPres_kpa

#convert kpa to meters of water
# constant, 1 kpa = 0.101972 m water
WL_01$WL_m <- WL_01$Corrected_kpa * 0.101972
WL_01$Corrected_kpa <- NULL

```
#plot data
```{r plot final, echo=FALSE}

##Now we can graph 
    ## will need to change the right limit accordingly

ggplot(data = WL_01 %>% filter(DateTime > "2021-06-10"), 
       aes(DateTime, WL_m)) +
  geom_point(color = "steelblue") +
  labs(title = "Station 01 Water level",
    y = "water level [m]", x = "") 

```